/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package roman.numerals;

import java.util.Scanner;

public class App {

    public static void main(String[] args) {
        final Scanner scanner = new Scanner(System.in);

        final RomanToArabicConverter converter = new RomanToArabicConverter();
        final String input = scanner.nextLine();
        final int arabicNumber = converter.convert(input);
        System.out.println(String.format("%s = %s",input, arabicNumber));
    }
}
